[[redirects]]
  from = "/volunteer"
  to = "/ThankYou.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/ThankYou.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "."
  command = ""